server:
  port: 9180

spring:
  application:
   name: order-service
  

eureka:
  client:
   register-with-eureka: true
   service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
      

      
     